name: Docker Image CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v1 
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD) name=branch::$(GITHUB_REF##*/)"
    - name: Build
      run: docker build -t antempus/azurefunctionsimage:$(steps.vars.outputs.branch)-$(steps.vars.outputs.sha_short) .

