name: Docker Image CI
git_hash = $(git rev-parse --short "$GITHUB_SHA")
git_branch=${GITHUB_REF##*/}
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v1 
    - name: Branch name
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Build
      run: docker build -t antempus/azurefunctionsimage:${GITHUB_REF##*/} .

